<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net6.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AcceptNPOIOSMFLicense>true</AcceptNPOIOSMFLicense>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <Import Project="../../common.props" />

  <ItemGroup Condition="'$(TargetFramework)'=='netstandard2.0'">
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageReference Include="NPOI" Version="2.8.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wodsoft.ComBoost.ExcelExport\Wodsoft.ComBoost.ExcelExport.csproj" />
  </ItemGroup>
</Project>
