<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Wodsoft.ComBoost.ExcelExport</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <Import Project="../../common.props" />

</Project>
