name: .NET

on:
  push:
    branches: [ next ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Pack
      run: dotnet pack --configuration Release /src/Wodsoft.ComBoost.Core/Wodsoft.ComBoost.Core.csproj --version-suffix "${{github.run_id}}"
    - name: Publish package
      run: dotnet nuget push /src/Wodsoft.ComBoost.Core/bin/Release/*.symbols.nupkg -k ${{secrets.MYGET_TOKEN}} -s https://www.myget.org/F/comboost/api/v2/package
